### ISSUE TITLE
Use $log instead of console.log

### ISSUE THREAD

**Issue by mmaday** [ryandrewjohnson/ui-router.grant#2]
The error statements should probably use Angular's built-in $log provider (https://docs.angularjs.org/api/ng/service/$log) rather than console.log.  This allows implementers to customize $log as they see fit.

**Comment by mmaday** [comment]
Hey Ryan, 

Looks like this change introduced a bug.  On the injection:

.run(['$rootScope', '$state', 'GRANT_ERROR', function($rootScope, $state, $log, GRANT_ERROR)

You never included the '$log'..

**Comment by ryandrewjohnson** [comment]
@mmaday good catch again. Not sure why I wasn't getting the error when I was testing, but should be good now. Please test on your end.

**Comment by mmaday** [comment]
Looking good!  Thanks.
