### ISSUE TITLE
Nested Resolves Are Called Even When Parent Grant Condition Not Resolved

### ISSUE THREAD

**Issue by joelcdoyle** [ryandrewjohnson/ui-router.grant#3]
I have a simple setup where a grant is used to make sure the user is logged in before proceeding:

```
  grant.addTest('loggedIn', function(grant){
    return Parse.User.current();
  });
```

This is used on an abstract route to prevent children from being reached without first being logged in:

```
  .state('app', {
    url: '/app',
    abstract: true,
    templateUrl: 'templates/app/menu.html',
    controller: 'AppCtrl',
    resolve: {
      loggedIn: function(grant) {
        return grant.only({test: 'loggedIn', state: 'login'});
      }
    }
  })
  .state('app.students', {
    url: '/students',
    views: {
      'menuContent': {
        templateUrl: 'templates/app/students.html',
        controller: 'StudentsCtrl'
      }
    },
    resolve: {
      students: function(StudentService, $ionicLoading) {
        return StudentService.getStudents(); //this breakpoint still reached if user not logged in
      }
    }
  })

```

The problem is, the resolve on the app.students state, `students` is being evaluated even if the user is not logged in. If I type `/app/students` in the url box and hit enter, the breakpoint for the `students` resolve is hit. It seems like no part of the route should be executed if the grant is not resolved positively.

**Comment by ryandrewjohnson** [comment]
The problem is that resolves are not necessarily handled synchronously or in the order they are listed. In order to ensure that the `loggedIn` test is run before the `students` resolve you need to pass the result of the loggedIn resolve as parameter to the students resolve. 

So your student resolve would look like this. I have added `loggedIn` as a param to the students resolve function.

```
.state('app.students', {
    url: '/students',
    views: {
      'menuContent': {
        templateUrl: 'templates/app/students.html',
        controller: 'StudentsCtrl'
      }
    },
    resolve: {
      students: function(loggedIn, StudentService, $ionicLoading) {
        return StudentService.getStudents(); //this breakpoint still reached if user not logged in
      }
    }
  })
```

I go over this in more detail in the [Working with nested states](https://github.com/ryandrewjohnson/ui-router.grant#working-with-nested-states). Here's the example I use:

```
.state('parent', {
  abstract: true,
  template: '<div ui-view></div>',
  resolve: {
    member: function(grant) {
      return grant.only({test: 'member', state: 'denied'});
    }
  }
})

  .state('parent.child1', {
    url: '/nested',
    templateUrl: 'partials/nested.html',
    resolve: {
      admin: function(grant, member) {
        // by injecting the member resolve key from the 'parent' state
        // we ensure that the member grant test will be completed before
        // the admin test executes in the 'parent.child1' state.
        return grant.only({test: 'admin', state: 'denied'});
      }
    }
  })
```

Let me know if this works. In all honesty it's been a while since I've worked with the project.

**Comment by joelcdoyle** [comment]
Thank you. Everything you say is correct. I'm using Ionic in my particular case, and it turns out that a route resolve that is rejected does not necessarily prevent the state from changing. It does, however, trigger the `$stateChangeError` event, that has to be caught manually using a global event watcher:

```
$rootScope.$on("$stateChangeError", function(event, toState, toParams, fromState, fromParams, error) {
  if(toState.name == "app.whatever") {
    $state.go('login');
  }
});
```

That's what I ended up going with. I'm using grant in another simpler web app and it works great!
