### ISSUE TITLE
Test member or admin

### ISSUE THREAD

**Issue by ablaye** [ryandrewjohnson/ui-router.grant#4]
Hello congratulations for this tool. It's very inspired and usefull. However, I can't test if member or admin with this `combined: function(grant) {
                  return grant.only([{test: 'admin', state: 'connexion'}, {test: 'member', state: 'connexion'}]);
                }`

It always to 'connexion' state

**Comment by ryandrewjohnson** [comment]
Please provide a Plunkr demonstrating the issue then I can have a look.

Thanks,

**Comment by ryandrewjohnson** [comment]
I have yet to receive a Plunker demonstrating the issue so I will be closing this.
