### ISSUE TITLE
Angular 1.5

### ISSUE THREAD

**Issue by dub34** [ryandrewjohnson/ui-router.grant#5]
Hi. Is it possible to use this module with angular 1.5.\* ? In your dependencies only 1.3

**Comment by ryandrewjohnson** [comment]
I have tried upgrading the plunker [demo](http://embed.plnkr.co/ZGqErbaJIYnZBaBhdnt1/preview) to use Angular 1.5 and the latest ui-router 0.2.x and it appears to work fine.

So even though the dependency requirements in the bower.json are out of date the plugin should work fine if you use it in an Angular 1.5 project.

**Comment by dub34** [comment]
it`s impossible to install it with your current bower.json.
When i try to install it, i get error 

> bower-asset/angular-ui-router-grant 0.1.4 requires bower-asset/angular ~1.3.14 -> no matching package found.

Can you update your dependencies or i fork your repository?

**Comment by ryandrewjohnson** [comment]
Just pushed fix in bower.json should be good now.

**Comment by dub34** [comment]
thank you
